# This is a basic workflow to help you get started with Actions
name: Run Spectral on Pull Requests

on:
  - pull_request
#   schedule:
#   - cron: "0 2 * * 1-5"


  
  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: oas.yaml
          spectral_ruleset: gitops/greetings.spectral.yaml
