# This is a basic workflow to help you get started with Actions
name: Run Spectral on Pull Requests

on:
  schedule:
  - cron: "0 2 * * 1-5"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.2
        with:
          file_glob: oas.yaml
          spectral_ruleset: gitops/greetings.spectral.yaml
